name: infrastructure
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  domain:
    path: ../domain
  drift: ^2.13.0
  get_it: ^7.6.4
  injectable: ^2.3.2
  injectable_generator: ^2.4.1
  path: ^1.8.3
  path_provider: ^2.0.0
  sqlite3_flutter_libs: ^0.5.0
  very_good_analysis: ^5.1.0

dev_dependencies:
  build_runner: ^2.4.6
  drift_dev: ^2.13.0
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
